import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';

function drupal_eval(php_source) {
  return execFileSync('docker', ['exec', 'blog_jurenites_web', 'vendor/bin/drush', 'php:eval', php_source], { encoding: 'utf8' }).trim();
}

const browser_instance = await chromium.launch({ headless: true });
const admin_page = await browser_instance.newPage({ viewport: { width: 1440, height: 1000 } });
const public_page = await browser_instance.newPage({ viewport: { width: 1440, height: 1000 } });
const test_label = 'Footer editor browser fixture';
const russian_label = 'Проверка редактора футера';
try {
  const login_url = execFileSync('docker', ['exec', 'blog_jurenites_web', 'vendor/bin/drush', 'user:login', '--uid=1', '--uri=http://jurenites.local'], { encoding: 'utf8' }).trim();
  await admin_page.goto(login_url, { waitUntil: 'domcontentloaded' });
  await admin_page.goto('http://jurenites.local/admin/structure/menu/manage/footer', { waitUntil: 'domcontentloaded' });
  assert.equal(await admin_page.getByRole('link', { name: 'Social networks', exact: true }).count() > 0 || await admin_page.getByText('Social networks', { exact: true }).count() > 0, true);
  await mkdir('artifacts/footer-menu', { recursive: true });
  await admin_page.screenshot({ path: 'artifacts/footer-menu/menu-editor.png', fullPage: true });
  await admin_page.goto('http://jurenites.local/admin/structure/menu/manage/footer/add', { waitUntil: 'domcontentloaded' });
  await admin_page.locator('[name="title[0][value]"]').fill(test_label);
  await admin_page.locator('[name="link[0][uri]"]').fill('https://example.com/footer-editor-test');
  const parent_options = await admin_page.locator('[name="menu_parent"] option').evaluateAll((option_nodes) => option_nodes.map((option_node) => ({ option_value: option_node.value, option_label: option_node.textContent })));
  const first_parent = parent_options.find((parent_option) => parent_option.option_label.includes('Social networks'));
  const second_parent = parent_options.find((parent_option) => parent_option.option_label.includes('How I work'));
  assert.ok(first_parent && second_parent);
  await admin_page.locator('[name="menu_parent"]').selectOption(first_parent.option_value);
  await admin_page.locator('[name="field_footer_icon"]').selectOption('brand-figma');
  await admin_page.locator('[name="field_footer_hover_paint[0][value]"]').fill('linear-gradient(90deg, var(--color-palette-brand-primary), var(--color-palette-brand-tertiary))');
  await admin_page.locator('[name="field_footer_hover_text[0][value]"]').fill('Editable hover example');
  await admin_page.locator('[name="field_footer_new_window[value]"]').check();
  await admin_page.screenshot({ path: 'artifacts/footer-menu/link-editor.png', fullPage: true });
  await admin_page.getByRole('button', { name: 'Save', exact: true }).click();
  await admin_page.waitForLoadState('domcontentloaded');
  console.log('Native create and presentation fields saved.');
  const link_id = drupal_eval('$menu_items = \\Drupal::entityTypeManager()->getStorage("menu_link_content")->loadByProperties(["menu_name" => "footer", "title" => "Footer editor browser fixture"]); echo reset($menu_items)->id();');
  assert.match(link_id, /^\d+$/);
  await public_page.goto('http://jurenites.local/', { waitUntil: 'domcontentloaded' });
  const cookie_close = public_page.locator('.cookie-policy-notice__close');
  if (await cookie_close.isVisible()) await cookie_close.click();
  const test_link = public_page.locator('.footer-navigation').getByRole('link', { name: /Footer editor browser fixture/ });
  assert.equal(await test_link.evaluate((link_node) => link_node.classList.contains('footer-navigation__link--gradient')), true);
  assert.equal(await test_link.getAttribute('style'), null);
  assert.equal(await test_link.getAttribute('target'), '_blank');
  await public_page.bringToFront();
  await test_link.scrollIntoViewIfNeeded();
  await test_link.hover();
  assert.equal(await test_link.locator('.footer-navigation__social-label-text--hover').evaluate((text_node) => getComputedStyle(text_node).visibility), 'visible');
  await public_page.mouse.move(0, 0);
  await test_link.focus();
  await test_link.press('Tab');
  await public_page.keyboard.press('Shift+Tab');
  assert.equal(await test_link.evaluate((link_node) => link_node.matches(':focus-visible')), true);
  assert.equal(await test_link.locator('.footer-navigation__social-label-text--hover').evaluate((text_node) => getComputedStyle(text_node).visibility), 'visible');
  assert.match(await test_link.locator('.footer-navigation__hover-text').evaluate((text_node) => getComputedStyle(text_node).backgroundImage), /^linear-gradient/);
  assert.equal(await test_link.locator('.footer-navigation__hover-text').evaluate((text_node) => getComputedStyle(text_node).color), 'rgba(0, 0, 0, 0)');
  assert.notEqual(await test_link.locator('.footer-navigation__social-network-icon').evaluate((icon_node) => getComputedStyle(icon_node).color), 'rgba(0, 0, 0, 0)');
  console.log('Public gradient hover and keyboard presentation verified.');
  await admin_page.goto(`http://jurenites.local/admin/structure/menu/item/${link_id}/edit/translations/add/en/ru`, { waitUntil: 'domcontentloaded' });
  await admin_page.locator('[name="title[0][value]"]').fill(russian_label);
  await admin_page.locator('[name="field_footer_hover_text[0][value]"]').fill('Текст при наведении');
  await admin_page.getByRole('button', { name: 'Save', exact: true }).click();
  await admin_page.waitForLoadState('domcontentloaded');
  console.log('Native Russian translation saved.');
  await public_page.goto('http://jurenites.local/ru', { waitUntil: 'domcontentloaded' });
  assert.equal(await public_page.locator('.footer-navigation').getByRole('link', { name: /Проверка редактора футера: Текст при наведении/ }).count(), 1);
  await admin_page.goto(`http://jurenites.local/admin/structure/menu/item/${link_id}/edit`, { waitUntil: 'domcontentloaded' });
  await admin_page.locator('[name="menu_parent"]').selectOption(second_parent.option_value);
  await admin_page.getByRole('button', { name: 'Save', exact: true }).click();
  await admin_page.waitForLoadState('domcontentloaded');
  await public_page.goto('http://jurenites.local/', { waitUntil: 'domcontentloaded' });
  assert.equal(await public_page.locator('.footer-navigation nav[aria-label="How I work"]').getByRole('link', { name: /Footer editor browser fixture/ }).count(), 1);
  await admin_page.goto(`http://jurenites.local/admin/structure/menu/item/${link_id}/edit`, { waitUntil: 'domcontentloaded' });
  await admin_page.locator('[name="enabled[value]"]').uncheck();
  await admin_page.getByRole('button', { name: 'Save', exact: true }).click();
  await admin_page.waitForLoadState('domcontentloaded');
  await public_page.goto('http://jurenites.local/', { waitUntil: 'domcontentloaded' });
  assert.equal(await public_page.locator('.footer-navigation').getByRole('link', { name: /Footer editor browser fixture/ }).count(), 0);
  await public_page.locator('.footer-navigation').screenshot({ path: 'artifacts/footer-menu/footer-desktop.png' });
  await public_page.setViewportSize({ width: 375, height: 900 });
  await public_page.locator('.footer-navigation').screenshot({ path: 'artifacts/footer-menu/footer-mobile.png' });
  assert.equal(await public_page.evaluate(() => document.documentElement.scrollWidth), 375);
  console.log('PASS: native editor create, icon/color/hover controls, keyboard focus, translation, reparent, disable, mobile overflow.');
} finally {
  drupal_eval('foreach (\\Drupal::entityTypeManager()->getStorage("menu_link_content")->loadByProperties(["menu_name" => "footer", "title" => "Footer editor browser fixture"]) as $menu_item) { $menu_item->delete(); }');
  await browser_instance.close();
}
