import { chromium } from 'playwright';
import { execFileSync } from 'node:child_process';
import assert from 'node:assert/strict';
const browser_instance = await chromium.launch({headless:true});
const page_instance = await browser_instance.newPage({viewport:{width:1300,height:1000}});
const runtime_errors=[];
page_instance.on('pageerror', error_value=>runtime_errors.push(error_value.message));
const login_url=execFileSync('docker',['exec','blog_jurenites_web','vendor/bin/drush','user:login','--uid=1','--uri=http://jurenites.local'],{encoding:'utf8'}).trim();
await page_instance.goto(login_url);
await page_instance.goto('http://jurenites.local/node/add/page');
await page_instance.waitForFunction(()=>window.Drupal?.CKEditor5Instances?.size>0);
console.log(await page_instance.evaluate(()=>{
 const editor_instance=[...Drupal.CKEditor5Instances.values()][0];
 editor_instance.setData('<h2>Source preview</h2><p>A <strong>bold</strong> word &amp; <a href="https://example.com">a link</a>.</p><ul><li>First item</li><li>Second item</li></ul>');
 editor_instance.plugins.get('SourceEditing').isSourceEditingMode=true;
 return {plugin:editor_instance.plugins.has('SourceCode'),source:document.querySelector('.source-code textarea')?.value};
}));
const source_area=page_instance.locator('.source-code textarea').first();
await source_area.waitFor();
await source_area.scrollIntoViewIfNeeded();
assert.ok(await page_instance.locator('.source-code__tag').count()>0);
await page_instance.locator('.source-code').screenshot({path:'/tmp/jurenites-source-editor.png'});
console.log(await source_area.evaluate(source_area=>{ const highlight_layer=source_area.parentElement.querySelector('pre');return {textarea:getComputedStyle(source_area).cssText,font:getComputedStyle(source_area).font,highlight_font:getComputedStyle(highlight_layer).font,color:getComputedStyle(highlight_layer.querySelector('span')).color};}));
await source_area.fill('<p>First</p><p>Second <strong>bold</strong> word.</p>');
await page_instance.locator('.source-code__format').click();
assert.match(await source_area.inputValue(), /\n/);
await source_area.evaluate(source_area=>{source_area.value='<p>Pasted</p><p>Next</p>';source_area.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertFromPaste'}));});
assert.match(await source_area.inputValue(), /\n/);
assert.equal(await page_instance.locator('.source-code__highlight').textContent(),(await source_area.inputValue())+'\n');
console.log(await page_instance.evaluate(()=>{const editor_instance=[...Drupal.CKEditor5Instances.values()][0];editor_instance.plugins.get('SourceEditing').isSourceEditingMode=false; const result_data=editor_instance.getData();editor_instance.plugins.get('SourceEditing').isSourceEditingMode=true;return result_data;}));
assert.equal(await page_instance.locator('.source-code__highlight').count(),1);
await source_area.fill('<p title="a > b">Safe &amp; <strong>inline</strong> text.</p><pre>  keep\n    spacing</pre>');
await page_instance.locator('.source-code__format').click();
assert.match(await source_area.inputValue(), /<pre>  keep\n    spacing<\/pre>/);
assert.equal(await page_instance.locator('.source-code__value').first().textContent(), '"a > b"');
await page_instance.evaluate(()=>[...Drupal.CKEditor5Instances.values()][0].enableReadOnlyMode('test'));
assert.equal(await source_area.getAttribute('readonly'), '');
assert.equal(await page_instance.locator('.source-code__format').isDisabled(), true);
await page_instance.evaluate(()=>[...Drupal.CKEditor5Instances.values()][0].disableReadOnlyMode('test'));
await page_instance.setViewportSize({width:390,height:844});
assert.equal(await source_area.evaluate(source_area=>getComputedStyle(source_area).font===getComputedStyle(source_area.parentElement.querySelector('pre')).font),true);
assert.deepEqual(runtime_errors,[]);
console.log('PASS: plugin, highlighting, formatting, paste, data sync, toggle, no runtime errors');
await browser_instance.close();
