map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

resolver 127.0.0.11 valid=10s;

server {
  listen 80;
  server_name jurenites.local;

  location / {
    set $drupal_upstream web:80;
    proxy_pass http://$drupal_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}

server {
  listen 80;
  server_name storybook.jurenites.local;

  location / {
    set $storybook_upstream storybook:6006;
    proxy_pass http://$storybook_upstream;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
  }
}

server {
  listen 80 default_server;
  server_name _;
  return 404;
}
