// Token build engine.
//
// Reads src/token/tokens.yaml directly, resolves {dot.path} references, and emits
// generated artifacts for CSS and JS consumers.

import { spawnSync } from 'node:child_process';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS_SOURCE = resolve(ROOT, 'src/token/tokens.yaml');
const OUTPUT_SCSS = resolve(ROOT, 'generated/styles/_tokens.scss');
const OUTPUT_JS = resolve(ROOT, 'generated/token/tokens.js');
const OUTPUT_COLOR_MAPPINGS = resolve(ROOT, 'generated/token/color-mappings.json');
const REFERENCE_PATTERN = /^\{([^{}]+)\}$/;
const PLAIN_REFERENCE_PATTERN = /^[a-z0-9-]+(?:\.[a-z0-9-]+)+$/;
const RAW_COLOR_HEX_PATTERN = /^#[0-9A-F]{6}$/;
const DIMENSION_PATTERN = /^-?(?:\d+\.?\d*|\.\d+)(?:px|rem|em|vh|vw|%|ch)$/;
const DURATION_PATTERN = /^-?(?:\d+\.?\d*|\.\d+)(?:ms|s)$/;
const SHADOW_VALUE_KEYS = ['offsetX', 'offsetY', 'blur', 'spread', 'color'];
// Generic family keywords must stay unquoted; project font names are quoted so
// names containing spaces or starting with a digit remain valid CSS.
const GENERIC_FONT_FAMILIES = new Set([
  'serif',
  'sans-serif',
  'monospace',
  'cursive',
  'fantasy',
  'system-ui',
]);
// Token groups that are documentation/metadata only and must not become CSS variables.
const EXCLUDED_NAME_PREFIXES = ['system-naming'];
const GENERATED_HEADER = '/* GENERATED by scripts/build-tokens.mjs. Do not edit by hand. Edit src/token/tokens.yaml instead. */';

function color_schema_error(token_path, error_message) {
  throw new Error(`Invalid color schema at ${token_path}: ${error_message}`);
}

function normalizePaletteValues(palette_group, palette_descriptions = {}) {
  if (!palette_group || typeof palette_group !== 'object' || Array.isArray(palette_group)) {
    color_schema_error('color.palette', 'expected a map of palette roles.');
  }

  return Object.fromEntries(Object.entries(palette_group).map(([palette_role, color_entry]) => {
    const token_path = `color.palette.${palette_role}`;
    if (typeof color_entry !== 'string' || !RAW_COLOR_HEX_PATTERN.test(color_entry)) {
      color_schema_error(token_path, 'expected one six-digit HEX string with uppercase A-F.');
    }

    return [palette_role, {
      $type: 'color',
      $value: color_entry,
      $description: palette_descriptions[palette_role] || palette_role.replaceAll('-', ' '),
    }];
  }));
}

function paletteDescriptionValues(source_content) {
  const palette_section = source_content.match(/^  palette:\n([\s\S]*?)^# Layer 2:/m)?.[1] || '';
  return Object.fromEntries(
    [...palette_section.matchAll(/^    ([a-z0-9-]+):\s*"#[0-9A-F]{6}"\s*#\s*(.+?)\s*$/gm)]
      .map((description_match) => [description_match[1], description_match[2]]),
  );
}

function inlineDescriptionValues(source_content) {
  const path_segments = [];
  const description_entries = [];

  for (const source_line of source_content.split('\n')) {
    const key_match = source_line.match(/^(\s*)([a-zA-Z0-9-]+):(?:\s+.*?)?\s+#\s+(.+)$/);
    const group_match = source_line.match(/^(\s*)([a-zA-Z0-9-]+):\s*$/);
    const matched_line = key_match || group_match;
    if (!matched_line) {
      continue;
    }

    const depth = matched_line[1].length / 2;
    path_segments.length = depth;
    path_segments[depth] = matched_line[2];
    if (key_match) {
      description_entries.push([path_segments.slice(0, depth + 1).join('.'), key_match[3].trim()]);
    }
  }

  return Object.fromEntries(description_entries);
}

function isShadowValue(token_value) {
  return token_value
    && typeof token_value === 'object'
    && !Array.isArray(token_value)
    && SHADOW_VALUE_KEYS.every((shadow_key) => Object.hasOwn(token_value, shadow_key));
}

function conciseReferenceValue(token_value) {
  if (typeof token_value === 'string' && PLAIN_REFERENCE_PATTERN.test(token_value)) {
    return `{${token_value}}`;
  }
  if (Array.isArray(token_value)) {
    return token_value.map(conciseReferenceValue);
  }
  if (token_value && typeof token_value === 'object') {
    return Object.fromEntries(
      Object.entries(token_value).map(([value_key, nested_value]) => [value_key, conciseReferenceValue(nested_value)]),
    );
  }
  return token_value;
}

function normalizeConciseTokens(source_node, path_segments, source_descriptions) {
  const token_path = path_segments.join('.');
  if (source_node && typeof source_node === 'object' && source_node.$value !== undefined) {
    return source_node;
  }
  if (Array.isArray(source_node) || isShadowValue(source_node) || source_node === null || typeof source_node !== 'object') {
    return {
      $value: conciseReferenceValue(source_node),
      $description: source_descriptions[token_path] || '',
    };
  }

  return Object.fromEntries(
    Object.entries(source_node).map(([source_key, source_value]) => [
      source_key,
      normalizeConciseTokens(source_value, [...path_segments, source_key], source_descriptions),
    ]),
  );
}

function normalizeColorMappings(mapping_node, path_segments) {
  const token_path = path_segments.join('.');
  if (typeof mapping_node === 'string') {
    if (!PLAIN_REFERENCE_PATTERN.test(mapping_node)) {
      color_schema_error(token_path, 'expected an unquoted dot.path reference without braces.');
    }
    return { $type: 'color', $value: `{${mapping_node}}` };
  }
  if (!mapping_node || typeof mapping_node !== 'object' || Array.isArray(mapping_node)) {
    color_schema_error(token_path, 'expected a mapping group or unquoted dot.path reference.');
  }

  return Object.fromEntries(Object.entries(mapping_node).map(([mapping_key, mapping_value]) => {
    if (mapping_key.startsWith('$')) {
      color_schema_error(`${token_path}.${mapping_key}`, 'DTCG fields are not allowed in the concise color schema.');
    }
    return [mapping_key, normalizeColorMappings(mapping_value, [...path_segments, mapping_key])];
  }));
}

export function normalizeColorSchema(source_tree, palette_descriptions = {}) {
  if (!source_tree.color?.palette) {
    color_schema_error('color', 'the "palette" group is required.');
  }
  if (source_tree.color.value) {
    color_schema_error('color.value', 'the redundant value layer is not allowed; palette roles own HEX values directly.');
  }

  source_tree.color.palette = normalizePaletteValues(source_tree.color.palette, palette_descriptions);

  for (const [theme_name, theme_group] of Object.entries(source_tree.theme || {})) {
    source_tree.theme[theme_name] = normalizeColorMappings(theme_group, ['theme', theme_name]);
  }
  for (const [component_name, component_group] of Object.entries(source_tree.component || {})) {
    if (component_group?.color) {
      component_group.color = normalizeColorMappings(
        component_group.color,
        ['component', component_name, 'color'],
      );
    }
  }

  return source_tree;
}

function normalizeSourceSchema(source_tree, source_descriptions) {
  const normalized_tree = normalizeColorSchema(source_tree, paletteDescriptionValues(source_descriptions.source_content));

  return Object.fromEntries(Object.entries(normalized_tree).map(([root_key, root_value]) => {
    if (root_key === '$schema' || root_key === 'meta' || root_key === 'color' || root_key === 'theme') {
      return [root_key, root_value];
    }
    return [root_key, normalizeConciseTokens(root_value, [root_key], source_descriptions.inline_descriptions)];
  }));
}

export async function loadTokenTree(sourcePath = TOKENS_SOURCE) {
  const source_content = await readFile(sourcePath, 'utf8');
  const ruby = `
require "json"
require "date"
require "yaml"

source = ARGV.fetch(0)
data = YAML.safe_load(
  File.read(source),
  permitted_classes: [Date, Time, Symbol],
  aliases: true
)
STDOUT.write(JSON.generate(data))
`;

  const result = spawnSync('ruby', ['-e', ruby, sourcePath], {
    cwd: ROOT,
    encoding: 'utf8',
  });

  if (result.status !== 0) {
    throw new Error(result.stderr || `Failed to read token YAML at ${sourcePath}.`);
  }

  return normalizeSourceSchema(JSON.parse(result.stdout), {
    source_content,
    inline_descriptions: inlineDescriptionValues(source_content),
  });
}

/**
 * Look up a DTCG node by its dot path (for example "color.palette.neutral-50").
 */
function lookupByPath(tree, dotPath) {
  return dotPath.split('.').reduce((node, segment) => {
    if (node === undefined || node === null) {
      return undefined;
    }
    return node[segment];
  }, tree);
}

/**
 * Resolve a raw $value into its final primitive, following {references} recursively.
 */
function resolveValue(tree, rawValue, seenPaths = new Set()) {
  if (typeof rawValue === 'string') {
    const match = rawValue.match(REFERENCE_PATTERN);
    if (!match) {
      return rawValue;
    }
    const referencedPath = match[1];
    if (seenPaths.has(referencedPath)) {
      throw new Error(`Circular token reference detected at {${referencedPath}}.`);
    }
    seenPaths.add(referencedPath);
    const referencedNode = lookupByPath(tree, referencedPath);
    if (!referencedNode || referencedNode.$value === undefined) {
      throw new Error(`Unresolved token reference {${referencedPath}}.`);
    }
    return resolveValue(tree, referencedNode.$value, seenPaths);
  }
  if (Array.isArray(rawValue)) {
    return rawValue.map((nested_value) => resolveValue(tree, nested_value, new Set(seenPaths)));
  }
  if (rawValue && typeof rawValue === 'object') {
    return Object.fromEntries(
      Object.entries(rawValue).map(([value_key, nested_value]) => [
        value_key,
        resolveValue(tree, nested_value, new Set(seenPaths)),
      ]),
    );
  }
  return rawValue;
}

function inferredTokenType(token_path, token_value) {
  if (token_path[0] === 'color' || token_path[0] === 'theme' || token_path.includes('color')) {
    return 'color';
  }
  if (isShadowValue(token_value)) {
    return 'shadow';
  }
  if (token_path[0] === 'elevation' && token_path[1] === 'shadow') {
    return 'shadow';
  }
  if (Array.isArray(token_value)) {
    return token_path[0] === 'motion' && token_path[1] === 'easing' ? 'cubicBezier' : 'fontFamily';
  }
  if (token_path.at(-1) === 'font-family') {
    return 'fontFamily';
  }
  if (typeof token_value === 'number') {
    return 'number';
  }
  if (typeof token_value === 'string' && DURATION_PATTERN.test(token_value)) {
    return 'duration';
  }
  if (typeof token_value === 'string' && DIMENSION_PATTERN.test(token_value)) {
    return 'dimension';
  }
  return 'string';
}

/**
 * Walk the token tree and collect every leaf (a node that has $value).
 */
export function collectTokens(tree) {
  const collected = [];

  function walk(node, pathSegments) {
    const flattenedName = pathSegments.join('-');
    // Skip documentation/metadata groups before resolving so doc strings are never
    // mistaken for token references.
    if (EXCLUDED_NAME_PREFIXES.some((prefix) => flattenedName.startsWith(prefix))) {
      return;
    }
    if (node && typeof node === 'object' && node.$value !== undefined) {
      const resolved_value = resolveValue(tree, node.$value);
      collected.push({
        name: flattenedName,
        path: [...pathSegments],
        type: node.$type || inferredTokenType(pathSegments, resolved_value),
        description: node.$description || '',
        sourceValue: node.$value,
        value: resolved_value,
        isReference: typeof node.$value === 'string' && REFERENCE_PATTERN.test(node.$value),
        referencePath: typeof node.$value === 'string'
          ? node.$value.match(REFERENCE_PATTERN)?.[1] || null
          : null,
      });
      return;
    }
    if (node && typeof node === 'object') {
      for (const key of Object.keys(node)) {
        if (key.startsWith('$') || key === 'meta') {
          continue;
        }
        walk(node[key], [...pathSegments, key]);
      }
    }
  }

  walk(tree, []);
  return collected;
}

/**
 * Convert a resolved token value into a CSS-ready string based on its DTCG type.
 */
export function formatResolvedCssValue(token) {
  switch (token.type) {
    case 'fontFamily': {
      // Reason: custom family names can start with digits or include whitespace.
      // Quote every non-generic family so values such as "4pixel" parse reliably.
      const families = Array.isArray(token.value) ? token.value : [token.value];
      return families
        .map((family) => (GENERIC_FONT_FAMILIES.has(family) ? family : JSON.stringify(family)))
        .join(', ');
    }
    case 'cubicBezier':
      return `cubic-bezier(${token.value.join(', ')})`;
    case 'shadow': {
      const shadow = token.value;
      if (typeof shadow === 'string') {
        return shadow;
      }
      return `${shadow.offsetX} ${shadow.offsetY} ${shadow.blur} ${shadow.spread} ${shadow.color}`;
    }
    default:
      return String(token.value);
  }
}

export function formatCssValue(token) {
  if (token.referencePath) {
    return `var(--${token.referencePath.replaceAll('.', '-')})`;
  }

  return formatResolvedCssValue(token);
}

/**
 * Build the :root { --name: value; } block shared by SCSS and Storybook CSS.
 */
function buildRootBlock(tokens) {
  const declarations = tokens
    .map((token) => `  --${token.name}: ${formatCssValue(token)};`)
    .join('\n');
  return `:root {\n${declarations}\n}`;
}

function buildTokenJs(tokens) {
  const tokenRecords = tokens.map((token) => ({
    name: token.name,
    path: token.path,
    type: token.type,
    description: token.description,
    source_value: token.sourceValue,
    value: token.value,
    css_value: formatCssValue(token),
    resolved_css_value: formatResolvedCssValue(token),
    is_reference: token.isReference,
    reference_name: token.referencePath?.replaceAll('.', '-') || null,
  }));

  return `${GENERATED_HEADER}

export const TOKEN_RECORDS = ${JSON.stringify(tokenRecords, null, 2)};

export const TOKEN_VALUES = Object.fromEntries(
  TOKEN_RECORDS.map((token_record) => [token_record.name, token_record.resolved_css_value]),
);

export const TOKEN_CSS_VALUES = Object.fromEntries(
  TOKEN_RECORDS.map((token_record) => [token_record.name, token_record.css_value]),
);

export const TOKEN_DESCRIPTIONS = Object.fromEntries(
  TOKEN_RECORDS.map((token_record) => [token_record.name, token_record.description]),
);
`;
}

function mappingEntries(tokens, tokenFilter) {
  return Object.fromEntries(
    tokens
      .filter((token) => token.type === 'color' && tokenFilter(token))
      .map((token) => [`--${token.name}`, formatCssValue(token)]),
  );
}

function buildColorMappingsJson(tokens) {
  const mappingTables = {
    palette_registry: Object.fromEntries(
      tokens
        .filter((token) => token.type === 'color' && token.name.startsWith('color-palette-'))
        .map((token) => [`--${token.name}`, {
          display_name: token.description,
          value: formatResolvedCssValue(token),
        }]),
    ),
    theme_to_palette: mappingEntries(tokens, (token) => token.name.startsWith('theme-')),
    component_mappings: mappingEntries(tokens, (token) => token.name.startsWith('component-')),
  };

  return `${JSON.stringify(mappingTables, null, 2)}\n`;
}

/**
 * Build SCSS breakpoint variables, a map, and up/down/between mixins.
 * Reason: media query widths cannot use CSS custom properties, so breakpoints
 * must also exist as compile-time SCSS values.
 */
function buildBreakpointScss(tokens) {
  const breakpoints = tokens.filter((token) => token.name.startsWith('system-breakpoint-'));
  const variableLines = breakpoints
    .map((token) => `$${token.name}: ${token.value};`)
    .join('\n');
  const mapEntries = breakpoints
    .map((token) => `  "${token.name.replace('system-breakpoint-', '')}": ${token.value},`)
    .join('\n');

  return `${variableLines}

$breakpoints: (
${mapEntries}
);

@mixin breakpoint-up($name) {
  @media (min-width: map.get($breakpoints, $name)) {
    @content;
  }
}

@mixin breakpoint-down($name) {
  @media (max-width: map.get($breakpoints, $name)) {
    @content;
  }
}

@mixin breakpoint-between($from, $to) {
  @media (min-width: map.get($breakpoints, $from)) and (max-width: map.get($breakpoints, $to)) {
    @content;
  }
}`;
}

/**
 * Build one SCSS mixin per CSS-ready typography shorthand token.
 */
function buildTypographyMixinsScss(sourceTree) {
  const typography = sourceTree.typography || {};
  const roleNames = Object.keys(typography).filter(
    (role_name) => role_name !== 'font-family' && typeof typography[role_name]?.$value === 'string',
  );

  return roleNames
    .map((role_name) => `@mixin typography-${role_name} {\n  font: var(--typography-${role_name});\n}`)
    .join('\n\n');
}

function buildTypographyUtilitiesScss(sourceTree) {
  const typography = sourceTree.typography || {};
  const roleNames = Object.keys(typography).filter(
    (role_name) => role_name !== 'font-family' && typeof typography[role_name]?.$value === 'string',
  );

  return roleNames
    .map((role_name) => `.u-typography-${role_name} {\n  font: var(--typography-${role_name});\n}`)
    .join('\n\n');
}

function buildTokenUtilitiesScss(tokens) {
  const utilityBlocks = [];

  for (const token of tokens) {
    if (token.type === 'color') {
      utilityBlocks.push(`.u-bg-${token.name} {\n  background: var(--${token.name});\n}`);
      utilityBlocks.push(`.u-color-${token.name} {\n  color: var(--${token.name});\n}`);
    }
    if (token.type === 'dimension' && token.name.startsWith('space-scale-')) {
      utilityBlocks.push(`.u-width-${token.name} {\n  width: var(--${token.name});\n}`);
    }
    if (token.type === 'shadow' && token.name.startsWith('elevation-shadow-')) {
      utilityBlocks.push(`.u-shadow-${token.name} {\n  box-shadow: var(--${token.name});\n}`);
    }
  }

  return utilityBlocks.join('\n\n');
}

async function main() {
  await readFile(TOKENS_SOURCE, 'utf8');
  const sourceTree = await loadTokenTree();
  const tokens = collectTokens(sourceTree);
  const rootBlock = buildRootBlock(tokens);

  const scssContent = `${GENERATED_HEADER}
@use "sass:map";

${rootBlock}

${buildBreakpointScss(tokens)}

${buildTypographyMixinsScss(sourceTree)}

${buildTypographyUtilitiesScss(sourceTree)}

${buildTokenUtilitiesScss(tokens)}
`;

  await mkdir(dirname(OUTPUT_SCSS), { recursive: true });
  await mkdir(dirname(OUTPUT_JS), { recursive: true });
  await writeFile(OUTPUT_SCSS, scssContent);
  await writeFile(OUTPUT_JS, buildTokenJs(tokens));
  await writeFile(OUTPUT_COLOR_MAPPINGS, buildColorMappingsJson(tokens));

  console.log(`Built ${tokens.length} tokens:
- ${OUTPUT_SCSS}
- ${OUTPUT_JS}
- ${OUTPUT_COLOR_MAPPINGS}`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
