// Token build engine.
//
// Reads src/token/tokens.yaml directly, resolves {dot.path} references, and emits
// the one build artifact the app needs: generated/styles/_tokens.scss.

import { spawnSync } from 'node:child_process';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pathToFileURL } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS_SOURCE = resolve(ROOT, 'src/token/tokens.yaml');
const OUTPUT_SCSS = resolve(ROOT, 'generated/styles/_tokens.scss');
const REFERENCE_PATTERN = /^\{([^{}]+)\}$/;
const GENERIC_FONT_FAMILIES = new Set([
  'serif',
  'sans-serif',
  'monospace',
  'cursive',
  'fantasy',
  'system-ui',
  'ui-serif',
  'ui-sans-serif',
  'ui-monospace',
  'ui-rounded',
  'emoji',
  'math',
  'fangsong',
]);
// Token groups that are documentation/metadata only and must not become CSS variables.
const EXCLUDED_NAME_PREFIXES = ['system-naming'];
const GENERATED_HEADER = '/* GENERATED by scripts/build-tokens.mjs. Do not edit by hand. Edit src/token/tokens.yaml instead. */';

export async function loadTokenTree(sourcePath = TOKENS_SOURCE) {
  const ruby = `
require "json"
require "date"
require "yaml"

source = ARGV.fetch(0)
data = YAML.safe_load(
  File.read(source),
  permitted_classes: [Date, Time, Symbol],
  aliases: true
)
STDOUT.write(JSON.generate(data))
`;

  const result = spawnSync('ruby', ['-e', ruby, sourcePath], {
    cwd: ROOT,
    encoding: 'utf8',
  });

  if (result.status !== 0) {
    throw new Error(result.stderr || `Failed to read token YAML at ${sourcePath}.`);
  }

  return JSON.parse(result.stdout);
}

/**
 * Look up a DTCG node by its dot path (for example "color.palette.white").
 */
function lookupByPath(tree, dotPath) {
  return dotPath.split('.').reduce((node, segment) => {
    if (node === undefined || node === null) {
      return undefined;
    }
    return node[segment];
  }, tree);
}

/**
 * Resolve a raw $value into its final primitive, following {references} recursively.
 */
function resolveValue(tree, rawValue, seenPaths = new Set()) {
  if (typeof rawValue === 'string') {
    const match = rawValue.match(REFERENCE_PATTERN);
    if (!match) {
      return rawValue;
    }
    const referencedPath = match[1];
    if (seenPaths.has(referencedPath)) {
      throw new Error(`Circular token reference detected at {${referencedPath}}.`);
    }
    seenPaths.add(referencedPath);
    const referencedNode = lookupByPath(tree, referencedPath);
    if (!referencedNode || referencedNode.$value === undefined) {
      throw new Error(`Unresolved token reference {${referencedPath}}.`);
    }
    return resolveValue(tree, referencedNode.$value, seenPaths);
  }
  return rawValue;
}

/**
 * Walk the token tree and collect every leaf (a node that has $value).
 */
export function collectTokens(tree) {
  const collected = [];

  function walk(node, pathSegments) {
    const flattenedName = pathSegments.join('-');
    // Skip documentation/metadata groups before resolving so doc strings are never
    // mistaken for token references.
    if (EXCLUDED_NAME_PREFIXES.some((prefix) => flattenedName.startsWith(prefix))) {
      return;
    }
    if (node && typeof node === 'object' && node.$value !== undefined) {
      collected.push({
        name: flattenedName,
        path: [...pathSegments],
        type: node.$type,
        value: resolveValue(tree, node.$value),
        isReference: typeof node.$value === 'string' && REFERENCE_PATTERN.test(node.$value),
      });
      return;
    }
    if (node && typeof node === 'object') {
      for (const key of Object.keys(node)) {
        if (key.startsWith('$') || key === 'meta') {
          continue;
        }
        walk(node[key], [...pathSegments, key]);
      }
    }
  }

  walk(tree, []);
  return collected;
}

/**
 * Convert a resolved token value into a CSS-ready string based on its DTCG type.
 */
export function formatCssValue(token) {
  switch (token.type) {
    case 'fontFamily': {
      // Reason: custom family names can start with digits or include whitespace.
      // Quote every non-generic family so values such as "4pixel" parse reliably.
      const families = Array.isArray(token.value) ? token.value : [token.value];
      return families
        .map((family) => (GENERIC_FONT_FAMILIES.has(family) ? family : JSON.stringify(family)))
        .join(', ');
    }
    case 'cubicBezier':
      return `cubic-bezier(${token.value.join(', ')})`;
    case 'shadow': {
      const shadow = token.value;
      return `${shadow.offsetX} ${shadow.offsetY} ${shadow.blur} ${shadow.spread} ${shadow.color}`;
    }
    default:
      return String(token.value);
  }
}

/**
 * Build the :root { --name: value; } block shared by SCSS and Storybook CSS.
 */
function buildRootBlock(tokens) {
  const declarations = tokens
    .map((token) => `  --${token.name}: ${formatCssValue(token)};`)
    .join('\n');
  return `:root {\n${declarations}\n}`;
}

/**
 * Build SCSS breakpoint variables, a map, and up/down/between mixins.
 * Reason: media query widths cannot use CSS custom properties, so breakpoints
 * must also exist as compile-time SCSS values.
 */
function buildBreakpointScss(tokens) {
  const breakpoints = tokens.filter((token) => token.name.startsWith('system-breakpoint-'));
  const variableLines = breakpoints
    .map((token) => `$${token.name}: ${token.value};`)
    .join('\n');
  const mapEntries = breakpoints
    .map((token) => `  "${token.name.replace('system-breakpoint-', '')}": ${token.value},`)
    .join('\n');

  return `${variableLines}

$breakpoints: (
${mapEntries}
);

@mixin breakpoint-up($name) {
  @media (min-width: map.get($breakpoints, $name)) {
    @content;
  }
}

@mixin breakpoint-down($name) {
  @media (max-width: map.get($breakpoints, $name)) {
    @content;
  }
}

@mixin breakpoint-between($from, $to) {
  @media (min-width: map.get($breakpoints, $from)) and (max-width: map.get($breakpoints, $to)) {
    @content;
  }
}`;
}

/**
 * Build a SCSS mixin per Material typography role so components can apply a role
 * with one include instead of wiring four CSS variables each time.
 */
function buildTypographyMixinsScss(sourceTree) {
  const typography = sourceTree.typography || {};
  const roleNames = Object.keys(typography).filter(
    (key) => !key.startsWith('font-') && typography[key] && typeof typography[key] === 'object',
  );

  return roleNames
    .map((role) => {
      const properties = typography[role];
      const lines = [];
      const propertyToCss = {
        'font-family': 'font-family',
        'font-size': 'font-size',
        'font-weight': 'font-weight',
        'line-height': 'line-height',
        'letter-spacing': 'letter-spacing',
        'text-transform': 'text-transform',
      };
      for (const property of Object.keys(properties)) {
        const cssProperty = propertyToCss[property];
        if (!cssProperty) {
          continue;
        }
        lines.push(`  ${cssProperty}: var(--typography-${role}-${property});`);
      }
      return `@mixin typography-${role} {\n${lines.join('\n')}\n}`;
    })
    .join('\n\n');
}

function buildTypographyUtilitiesScss(sourceTree) {
  const typography = sourceTree.typography || {};
  const roleNames = Object.keys(typography).filter(
    (key) => !key.startsWith('font-') && typography[key] && typeof typography[key] === 'object',
  );

  return roleNames
    .map((role) => {
      const properties = typography[role];
      const lines = [];
      const propertyToCss = {
        'font-family': 'font-family',
        'font-size': 'font-size',
        'font-weight': 'font-weight',
        'line-height': 'line-height',
        'letter-spacing': 'letter-spacing',
        'text-transform': 'text-transform',
      };
      for (const property of Object.keys(properties)) {
        const cssProperty = propertyToCss[property];
        if (!cssProperty) {
          continue;
        }
        lines.push(`  ${cssProperty}: var(--typography-${role}-${property});`);
      }
      return `.u-typography-${role} {\n${lines.join('\n')}\n}`;
    })
    .join('\n\n');
}

async function main() {
  await readFile(TOKENS_SOURCE, 'utf8');
  const sourceTree = await loadTokenTree();
  const tokens = collectTokens(sourceTree);
  const rootBlock = buildRootBlock(tokens);

  const scssContent = `${GENERATED_HEADER}
@use "sass:map";

${rootBlock}

${buildBreakpointScss(tokens)}

${buildTypographyMixinsScss(sourceTree)}

${buildTypographyUtilitiesScss(sourceTree)}
`;

  await mkdir(dirname(OUTPUT_SCSS), { recursive: true });
  await writeFile(OUTPUT_SCSS, scssContent);

  console.log(`Built ${tokens.length} tokens:
- ${OUTPUT_SCSS}`);
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
