// Token build engine.
//
// Reads the generated token contract (generated/tokens/tokens.json, DTCG format), resolves
// {dot.path} references, flattens every token to a dash-separated name, and emits:
//   1. generated/styles/_tokens.scss                   (CSS custom properties + SCSS breakpoint vars/map/mixins + typography mixins)
//   2. generated/styles/tokens.css                     (CSS custom properties only)
//   3. generated/tokens/tokens.min.json                (minified contract, for runtime/Drupal/Figma transport)
//
// Reason: the editable source is src/token/tokens.yaml; Storybook, the Drupal theme,
// and Figma all derive from the generated JSON contract.

import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS_SOURCE = resolve(ROOT, 'generated/tokens/tokens.json');
const OUTPUT_SCSS = resolve(ROOT, 'generated/styles/_tokens.scss');
const OUTPUT_STORYBOOK_CSS = resolve(ROOT, 'generated/styles/tokens.css');
const OUTPUT_MIN_JSON = resolve(ROOT, 'generated/tokens/tokens.min.json');
const OUTPUT_FLAT_JSON = resolve(ROOT, 'generated/tokens/tokens.flat.json');
const REFERENCE_PATTERN = /^\{([^{}]+)\}$/;
const GENERIC_FONT_FAMILIES = new Set([
  'serif',
  'sans-serif',
  'monospace',
  'cursive',
  'fantasy',
  'system-ui',
  'ui-serif',
  'ui-sans-serif',
  'ui-monospace',
  'ui-rounded',
  'emoji',
  'math',
  'fangsong',
]);
// Token groups that are documentation/metadata only and must not become CSS variables.
const EXCLUDED_NAME_PREFIXES = ['system-naming'];
const GENERATED_HEADER = '/* GENERATED by scripts/build-tokens.mjs. Do not edit by hand. Edit src/token/tokens.yaml instead. */';

/**
 * Look up a DTCG node by its dot path (for example "color.palette.white").
 */
function lookupByPath(tree, dotPath) {
  return dotPath.split('.').reduce((node, segment) => {
    if (node === undefined || node === null) {
      return undefined;
    }
    return node[segment];
  }, tree);
}

/**
 * Resolve a raw $value into its final primitive, following {references} recursively.
 */
function resolveValue(tree, rawValue, seenPaths = new Set()) {
  if (typeof rawValue === 'string') {
    const match = rawValue.match(REFERENCE_PATTERN);
    if (!match) {
      return rawValue;
    }
    const referencedPath = match[1];
    if (seenPaths.has(referencedPath)) {
      throw new Error(`Circular token reference detected at {${referencedPath}}.`);
    }
    seenPaths.add(referencedPath);
    const referencedNode = lookupByPath(tree, referencedPath);
    if (!referencedNode || referencedNode.$value === undefined) {
      throw new Error(`Unresolved token reference {${referencedPath}}.`);
    }
    return resolveValue(tree, referencedNode.$value, seenPaths);
  }
  return rawValue;
}

/**
 * Walk the token tree and collect every leaf (a node that has $value).
 */
function collectTokens(tree) {
  const collected = [];

  function walk(node, pathSegments) {
    const flattenedName = pathSegments.join('-');
    // Skip documentation/metadata groups before resolving so doc strings are never
    // mistaken for token references.
    if (EXCLUDED_NAME_PREFIXES.some((prefix) => flattenedName.startsWith(prefix))) {
      return;
    }
    if (node && typeof node === 'object' && node.$value !== undefined) {
      collected.push({
        name: flattenedName,
        path: [...pathSegments],
        type: node.$type,
        value: resolveValue(tree, node.$value),
        isReference: typeof node.$value === 'string' && REFERENCE_PATTERN.test(node.$value),
      });
      return;
    }
    if (node && typeof node === 'object') {
      for (const key of Object.keys(node)) {
        if (key.startsWith('$') || key === 'meta') {
          continue;
        }
        walk(node[key], [...pathSegments, key]);
      }
    }
  }

  walk(tree, []);
  return collected;
}

/**
 * Convert a resolved token value into a CSS-ready string based on its DTCG type.
 */
function formatCssValue(token) {
  switch (token.type) {
    case 'fontFamily': {
      // Reason: custom family names can start with digits or include whitespace.
      // Quote every non-generic family so values such as "4pixel" parse reliably.
      const families = Array.isArray(token.value) ? token.value : [token.value];
      return families
        .map((family) => (GENERIC_FONT_FAMILIES.has(family) ? family : JSON.stringify(family)))
        .join(', ');
    }
    case 'cubicBezier':
      return `cubic-bezier(${token.value.join(', ')})`;
    case 'shadow': {
      const shadow = token.value;
      return `${shadow.offsetX} ${shadow.offsetY} ${shadow.blur} ${shadow.spread} ${shadow.color}`;
    }
    default:
      return String(token.value);
  }
}

/**
 * Build the :root { --name: value; } block shared by SCSS and Storybook CSS.
 */
function buildRootBlock(tokens) {
  const declarations = tokens
    .map((token) => `  --${token.name}: ${formatCssValue(token)};`)
    .join('\n');
  return `:root {\n${declarations}\n}`;
}

/**
 * Build SCSS breakpoint variables, a map, and up/down/between mixins.
 * Reason: media query widths cannot use CSS custom properties, so breakpoints
 * must also exist as compile-time SCSS values.
 */
function buildBreakpointScss(tokens) {
  const breakpoints = tokens.filter((token) => token.name.startsWith('system-breakpoint-'));
  const variableLines = breakpoints
    .map((token) => `$${token.name}: ${token.value};`)
    .join('\n');
  const mapEntries = breakpoints
    .map((token) => `  "${token.name.replace('system-breakpoint-', '')}": ${token.value},`)
    .join('\n');

  return `${variableLines}

$breakpoints: (
${mapEntries}
);

@mixin breakpoint-up($name) {
  @media (min-width: map.get($breakpoints, $name)) {
    @content;
  }
}

@mixin breakpoint-down($name) {
  @media (max-width: map.get($breakpoints, $name)) {
    @content;
  }
}

@mixin breakpoint-between($from, $to) {
  @media (min-width: map.get($breakpoints, $from)) and (max-width: map.get($breakpoints, $to)) {
    @content;
  }
}`;
}

/**
 * Build a SCSS mixin per Material typography role so components can apply a role
 * with one include instead of wiring four CSS variables each time.
 */
function buildTypographyMixinsScss(sourceTree) {
  const typography = sourceTree.typography || {};
  const roleNames = Object.keys(typography).filter(
    (key) => !key.startsWith('font-') && typography[key] && typeof typography[key] === 'object',
  );

  return roleNames
    .map((role) => {
      const properties = typography[role];
      const lines = [];
      const propertyToCss = {
        'font-family': 'font-family',
        'font-size': 'font-size',
        'font-weight': 'font-weight',
        'line-height': 'line-height',
        'letter-spacing': 'letter-spacing',
        'text-transform': 'text-transform',
      };
      for (const property of Object.keys(properties)) {
        const cssProperty = propertyToCss[property];
        if (!cssProperty) {
          continue;
        }
        lines.push(`  ${cssProperty}: var(--typography-${role}-${property});`);
      }
      return `@mixin typography-${role} {\n${lines.join('\n')}\n}`;
    })
    .join('\n\n');
}

async function main() {
  const sourceText = await readFile(TOKENS_SOURCE, 'utf8');
  const sourceTree = JSON.parse(sourceText);
  const tokens = collectTokens(sourceTree);
  const rootBlock = buildRootBlock(tokens);

  const scssContent = `${GENERATED_HEADER}
@use "sass:map";

${rootBlock}

${buildBreakpointScss(tokens)}

${buildTypographyMixinsScss(sourceTree)}
`;

  const storybookCssContent = `${GENERATED_HEADER}\n${rootBlock}\n`;
  const minifiedJson = JSON.stringify(sourceTree);

  // Flat resolved map: name -> { type, value, css }. Reason: Storybook foundations
  // and the Figma sync scripts both need fully-resolved values keyed by the same
  // dash names used as CSS variables, without re-implementing reference resolution.
  const flatMap = {};
  for (const token of tokens) {
    flatMap[token.name] = {
      type: token.type,
      value: token.value,
      css: formatCssValue(token),
      path: token.path,
      isReference: token.isReference,
    };
  }
  const flatJson = JSON.stringify(flatMap, null, 2);

  await mkdir(dirname(OUTPUT_SCSS), { recursive: true });
  await mkdir(dirname(OUTPUT_STORYBOOK_CSS), { recursive: true });
  await mkdir(dirname(OUTPUT_MIN_JSON), { recursive: true });

  await writeFile(OUTPUT_SCSS, scssContent);
  await writeFile(OUTPUT_STORYBOOK_CSS, storybookCssContent);
  await writeFile(OUTPUT_MIN_JSON, minifiedJson);
  await writeFile(OUTPUT_FLAT_JSON, flatJson);

  console.log(`Built ${tokens.length} tokens:
- ${OUTPUT_SCSS}
- ${OUTPUT_STORYBOOK_CSS}
- ${OUTPUT_MIN_JSON}
- ${OUTPUT_FLAT_JSON}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
